nonos/main.py, setup.cfg, tests/test_cli.py, tests/test_errors.py
Completely ignoring formatting nitpicks that can be solved automatically, I wrote a minimal config for flake8 which allows to detect noise and potentially critical errors (undefined variable, unused imports...)
Here's the result of a run so far.
```shell
$ flake8 .
./nonos/main.py:7:1: F401 'multiprocessing.Value' imported but unused
./nonos/main.py:871:15: E711 comparison to None should be 'if cond is None:'
./tests/test_errors.py:1:1: F401 'nonos.FieldNonos' imported but unused
./tests/test_errors.py:2:1: F401 'os' imported but unused
./tests/test_cli.py:3:1: F401 'toml' imported but unused
```
I'll fix those in the same PR, and next time we can add the check to CI to improve stability.
edit: done
=> static checking: add a minimal configuration for flake8

README.md, nonos/config.py, nonos/main.py, nonos/parsing.py, tests/test_load_config.py, tests/test_parsing.py, tests/test_plotting.py
fix #16
Replace `-mod`, `-onStart`, `-onEnd` and `-onStep` arguments with a single `-on` argument with some magic.
I realised that there's no easy replacement for
```shell
$ nonos -mod f
```
which means "grab everything you want and save an image", but I also note that this mode is a bit fragile because it won't work if some dump files are missing. For now, I'm replacing it with a `-film` arg, that I hope to be able to remove later, and which is implemented to be incompatible with this generalised `-on` param.
TODO
=> Output file(s) selection system revamp

README.md, nonos/config.py, nonos/main.py, nonos/parsing.py, tests/test_parsing.py, tests/test_plotting.py
fix #21
this is currently based ont top of #29 
TODO
=> expose image format selection

setup.cfg
I just released inifix 0.5.0
Basically it doesn't change anything on nonos' side, but there's a fix in there.
=> bump inifix required version

.pre-commit-config.yaml
set pre-commit.ci to autoupdate 3 times a years instead of each week
=> MNT: slow down autoupdate pace for pre-commit.ci

.github/workflows/ci.yml, .pre-commit-config.yaml, setup.cfg
Now that matplotlib 3.5.0 is out, there are wheels for Python 3.10 we can test against.
=> MNT: add explicit support for Python 3.10

.pre-commit-config.yaml, nonos/api/analysis.py, tests/test_parsing.py
This update is necessary because newest versions of click break black (see https://github.com/psf/black/issues/2964)
updating black is also going to cause small style changes that came with black 22
=> Update pre-commit hooks

.pre-commit-config.yaml
context: isort needs to be upgraded because our currently pinned version is not compatible with Python 3.11, which is used in ci, see https://results.pre-commit.ci/run/github/348780729/1675286583.-x8J6rRSSJy2dfyvyCS7-Q
=> MNT: upgrade pre-commit hooks

nonos/main.py, nonos/styling.py, pyproject.toml, requirements/minimal_dependencies.txt, requirements/typecheck.txt
=> BLD: drop pkg_resources as a dependency on Python 3.8

.github/workflows/ci.yml
This will probably not work just yet, depending how dependencies handled Python 3.11 compat thusfar
=> TST: switch CI to Python 3.11

constraints/minimal_dependencies.txt, nonos/main.py, pyproject.toml
=> ENH: avoid deprecated cblind API

README.md, nonos/styling.py
This was discovered thanks to newly supported type checking in matplotlib 3.8.0rc1
explanation: `matplotlib.style` is only defined at runtime *after* `pyplot` was imported. I also updated the documentation to avoid `AttributeErrors`
=> BUG: fix an insidious bug where nonos.styling.set_mpl_style silently relied on side effects to work with matplotlib >= 3.7

.github/workflows/bleeding-edge.yml, .github/workflows/ci.yml, pyproject.toml
requires that `scikit-image` and `lick` start publishing wheels for CPython 3.12
=> TST: test on Python 3.12

requirements/docs.txt
follow up to #223: I believe this requirement isn't supported by dependabot and explains why #217, #219 and #220 were closed. It's also not needed since we use a flat package layout (as opposed to a src layout)
=> TST: simplify doc requirements

nonos/_backports.py
Not immediately useful, just chunking out small bits from my big refactor.
=> ENH: backport `str.removesuffix` from Python 3.9

.pre-commit-config.yaml
It's a lot nicer to see *what* ruff changed in pre-commit.
=> MNT: enable ruff's --show-fixes flag

pyproject.toml, tests/test_errors.py, tests/test_params_usage.py
- **MNT: configure coverage**
- **TST: remove an unreachable line from test**
- **TST: mark failure modes from a meta test as un-coverable**
=> MNT: configure coverage

.github/workflows/ci.yml, requirements/tests.txt
At the time of opening, I set it to fail CI if coverage is reported < 100%, which is currently the case. I intend to lower or remove this barrier once it's the only remaining failure mode.
=> TST: generate coverage reports in CI

nonos/parsing.py
This avoids adding a test for an unused case.
=> RFC: make parse_range agnostic to physically meaningful dimensionalities

nonos/main.py, tests/test_plotting.py
This is basically the same idea as #255, but I have a new motivation for it: `nonos.main::process_field` is currently marked as not covered in reports, but I'm almost certain that it's just because multiprocessing or rich destroys traceback data.
=> BUG: avoid multiprocessing overhead when looping on a single worker

tests/test_interfaces/test_contracts.py
This fixes a non-user-facing bug in a test that I discovered in #299 (not sure why it wasn't visible before)
=> TST: fix a meta test

.github/workflows/ci.yml
I'm getting new, but seemingly unrelated type checking errors in #299, which I suspect would already happen on main, so let's try typechecking on all supported Python versions from now on
=> TYP: typecheck against every supported Python version

.pre-commit-config.yaml
Avoid messy branch histories like we're seeing right now <img width="458" alt="Screenshot 2024-04-05 at 22 54 35" src="https://github.com/volodia99/nonos/assets/14075922/64c54149-d7d6-4493-9e4b-bf648a5d3e7b">
=> MNT: deactivate pre-commit.ci autofixes

.pre-commit-config.yaml, README.md, nonos/_readers/binary.py, nonos/_readers/ini.py, nonos/_types.py, nonos/api/from_simulation.py, tests/test_cli.py, tests/test_interfaces/test_binary_readers.py, tests/test_interfaces/test_ini_readers.py, tests/test_interfaces/test_loader.py
In the few minor ways ruff-format diverges from black, it's actually better, so let's save a hook.
=> STY: migrate from black to ruff-format

nonos/api/analysis.py
avoiding a reference to phimed to simplify an upcoming, much more involved refactor
=> RFC: simplify GasField.find_iphi

nonos/api/analysis.py
This accomplishes two things:
- improve perfs (`np.ndarray.tolist` is about 10x faster than a listcomp here)
- clarify that we want to transform arrays, not "everything that's not geometry" (even if they're the same set in this context)
=> RFC: cleaner array serialization to json

nonos/_readers/binary.py
Fixes the critical part of #323. I'll follow up with a refactor to eliminate `Geometry.CYLINDRICAL`
=> BUG: fix a bug where FargoADSG datasets would be loaded using a broken geometry flag

nonos/_readers/binary.py, nonos/_types.py, tests/test_interfaces/test_binary_readers.py
A simplification towards fixing #323 but it's also revealing that we in fact do not already support cylindrical flags from idefix/pluto vtks.
=> RFC: drop Geometry CYLINDRICAL enum member

.github/workflows/bleeding-edge.yml, .github/workflows/ci.yml, requirements/tests_all.txt, requirements/tests_min.txt, tests/test_plotting.py
This is meant to resolve an issue [seen in last night's CI](https://github.com/volodia99/nonos/actions/runs/9672974485/job/26686174204) where numpy 2.0.0 was installed on the minimal deps jobs via numexpr (unconstrained), which is not compatible with matplotlib 3.5.0
=> TST: make numexpr an optional test dependency

nonos/main.py, pyproject.toml
I just released inifix 5.0.0, this is supposed to be the only required change in nonos
=> BUG: handle a deprecation in inifix 5.0.0

nonos/main.py
This eliminates a bug I stumbled into in #357
=> BUG: explicitly set non graphic matplotlib backend within CLI if there's nothing to show

nonos/main.py, nonos/styling.py
=> RFC: avoid pyplot interface in lib

tests/test_plotting.py
=> RFC: avoid pyplot interface in tests (1/2)

tests/test_image_comp.py
=> TST: improve state cleanup in test fixture

nonos/main.py, requirements/tests_all.txt, tests/test_plotting.py
In the process of removing cblind as a requirement, I also added support for other known colormap packages *if they are installed*. I'll need to add test coverage too before I undraft.
=> ENH: (CLI): support colormap extension packages other than cblind (cmasher, cmocean, cmyt)

pyproject.toml
[example logs](https://github.com/volodia99/nonos/actions/runs/12031859520/job/33542335020)
I already patched cmyt, and opened a PR for cmocean https://github.com/matplotlib/cmocean/pull/114
=> TST: filter a transitive deprecation warning from matplotlib 3.11 (dev)

.github/workflows/bleeding-edge.yml, .github/workflows/cd.yml, .github/workflows/ci.yml
Obtained via `gha-update`. Dependabot can still handle this format.
=> TST: pin and upgrade GitHub Actions

.github/workflows/cd.yml
- the current latest version of hatchling (1.27.0) using METADATA format 2.4
- pypa/gh-action-pypi-publish 1.12.2 not supporting this format version
=> REL: bump pypa/gh-action-pypi-publish

nonos/api/analysis.py
This is a more robust alternative to the first part of #384:
- I see no reason that this function should only return something meaningful *sometimes* (users are still free to not bind the return value)
- this fixes an inconsistency that `filename` had no effect if `title` was set
- the return type can be annotated without a union (`Axes.plot` returns a `list` of `Artist`, so the approach taken in #384 isn't consistent with its description)
=> BUG: make `Plotable.plot` return unconditionally

pyproject.toml
=> DEP: drop `cblind` as a hard dependency

nonos/logging.py, nonos/main.py, pyproject.toml
This is a step towards minimizing the total number of (direct+indirect) dependencies.
Switching to tqdm for progress bars also allows to fix a known bug where `-progressBar` has no effect with `-ncpu 1`
A minor setback I need to resolve is that tqdm doesn't interact with pytest as nicely as rich.progress, meaning that in `test_pbar`, we cannot accurately check wether the progress bar was cleaned up afterward, causing the test to fail, even though manual testing shows that the behavior matches what's intended.
=> DEP: drop dependency on `rich` (replaced by atomic dependencies `termcolor` + `tqdm`)

nonos/_readers/binary.py
=> BUG: fix reading coordinates in `Fargo3DReader.read`

uv.lock
```
Updated coverage v7.6.9 -> v7.6.10
Updated inifix v4.5.0, v5.1.2 -> v4.5.0, v5.1.3
Updated jinja2 v3.1.4 -> v3.1.5
Updated kiwisolver v1.4.7 -> v1.4.7, v1.4.8
Updated mypy v1.13.0 -> v1.14.1
Updated numpy v2.0.2, v2.2.0 -> v2.0.2, v2.2.1
Updated pyparsing v3.2.0 -> v3.2.1
```
=> DEP: lockfile maintenance

uv.lock
```
Updated griffe v1.5.4 -> v1.5.5
Updated importlib-resources v6.4.5 -> v6.5.2
Updated mkdocs-autorefs v1.2.0 -> v1.3.0
Updated mkdocs-material v9.5.49 -> v9.5.50
Updated numpy v2.0.2, v2.2.1 -> v2.0.2, v2.2.2
Updated pillow v11.0.0 -> v11.1.0
Updated pygments v2.18.0 -> v2.19.1
Updated pymdown-extensions v10.13 -> v10.14
Updated scipy v1.13.1, v1.14.1 -> v1.13.1, v1.15.1
```
=> DEP: manually bump uv.lock

nonos/api/from_simulation.py
This simple edit fixes 3 errors flagged by pyright (basic mode).
=> TYP: avoid defining a type alias as a regular variable

uv.lock
```
Updated babel v2.16.0 -> v2.17.0
Updated certifi v2024.12.14 -> v2025.1.31
Updated cmyt v2.0.0, v2.0.1 -> v2.0.0, v2.0.2
Updated fonttools v4.55.3 -> v4.55.8
Updated griffe v1.5.5 -> v1.5.6
Updated importlib-metadata v8.5.0 -> v8.6.1
Updated inifix v4.5.0, v5.1.3 -> v4.5.0, v6.0.0
Updated mkdocs-material v9.5.50 -> v9.6.2
Updated mkdocstrings v0.27.0 -> v0.28.0
Updated mkdocstrings-python v1.13.0 -> v1.14.4
Updated pymdown-extensions v10.14 -> v10.14.3
```
=> MNT: bump uv.lock

src/nonos/main.py
This single line is flagged multiple times by pyright because the `func_kwargs` dictionary has many unknown types. The root cause being that many of its values come straight from `argparse` APIs, which are basically un-checkable, so I'll ignore them for now (and probably for ever) to reduce the level of noise.
=> TYP: ignore an unfixable pyright error

pyproject.toml
Follow up to #359
Even better than hatchling for nonos' needs:
- 0 dependencies
- publish artifacts are minimal by default (while hatchling requires fine tuning)
=> BLD: switch build backend to `flit-core`

.pre-commit-config.yaml, README.md, src/nonos/api/analysis.py
Migrating because the `typos` repo tend to receive tags in a non-linear order, making auto-upgrades non-trivial to apply.
=> MNT: migrate typo-checker pre-commit hook (typos -> codespell)

src/nonos/__main__.py
`exit`, despite broad availability in REPLs (including the default one), isn't a built-in function.
=> BUG: correct exit method for `python -m nonos`

src/nonos/api/__init__.py
Immediate follow up to #463
For some reason ruff doesn't seem to detect this, even though [the corresponding rule](https://docs.astral.sh/ruff/rules/undefined-export/) is enabled.
=> BUG: fixup undefined names in dunder all
