- nonos/config.toml
formatted with
```
$ inifix-format nonos/config.toml
```
> use inifix-format on default config file

- nonos/main.py
- tests/test_plotting.py
this is again a mistake that I introduced in #10
TODO
> hotfix: -cor flag is broken

- nonos/logging.py
- nonos/main.py
- tests/test_cli.py
- tests/test_plotting.py
> isolated logging functionalities, add a bone emoji to err messages

- nonos/main.py
- setup.cfg
following https://github.com/neutrinoceros/inifix/pull/35 and https://github.com/neutrinoceros/inifix/pull/37
> bump inifix required version

- README.md
- nonos/config.py
- nonos/main.py
fix #22 
This is currently based on #17
TODO:
> expose image resolution parameter

- README.md
- nonos/main.py
- tests/test_plotting.py
> add display flag

- .pre-commit-config.yaml
- nonos/logging.py
- nonos/main.py
- nonos/parsing.py
- setup.cfg
- tests/test_cli.py
- tests/test_params_usage.py
- tests/test_plotting.py
> add flake8 to pre-commit toolbelt

- nonos/main.py
using np.memmap instead of np.fromfile + some tricks
to be tested on jzay
> memory efficient way of reading/storing vtk arrays

- README.md
- nonos/logging.py
- nonos/main.py
- tests/test_plotting.py
may be useful for future works
> verbose mode (light for now)

- nonos/config.py
- nonos/main.py
- nonos/parsing.py
> ongoing work: zoom (r,z)

- nonos/config.py
- nonos/main.py
- nonos/parsing.py
without rmin/rmax/zmin/zmax (aim: use zoom/center instead)
> older version of main 

- setup.cfg
following https://github.com/neutrinoceros/inifix/pull/50
> bump minimal inifix version to include latest bugfix

- .pre-commit-config.yaml
- nonos/main.py
- nonos/parsing.py
- setup.cfg
This is based on top of #52 because I find that the pure python toml implem
has too fuzy type annotations which confuse mypy.
> type checking with mypy

- tests/conftest.py
> TST: use non GUI matplotlib backend in tests

- nonos/api/analysis.py
- nonos/api/from_simulation.py
updated loadPlanetFile for fargo-adsg and added find_rp function in class GasField
> fix planet function for fargo-adsg + find_rp

- .github/workflows/ci.yml
- README.md
- nonos/main.py
- setup.cfg
- tests/test_readme.py
> MNT: use cog to auto update --help section in the REAMDE

- nonos/api/analysis.py
updated latitudinal_projection in polar and not implemented error for vertical projection in spherical
> update projection functions

- nonos/api/analysis.py
treatment of vmin vmax when norm in kwargs
> vmin vmax norm

- .github/workflows/ci.yml
- setup.cfg
- tests/test_plotting.py
- Add new tests for plotting API
- cleanup existing tests to reuse existing fixtures
- define a minimal env and test it
> TST: test cleanup + new tests

- nonos/main.py
In main.py, deal with vmin THEN vmax instead of mixing the operations on vmin and vmax
> bug fix vmin/vmax in CLI

- .git-blame-ignore-revs
- .pre-commit-config.yaml
- tests/data/idefix_newvtk_planet2d/idefix.ini
- tests/data/idefix_planet3d/idefix.ini
- tests/data/idefix_rwi/idefix.ini
> ENH: upgrade pre-commit hooks

- nonos/api/analysis.py
- nonos/api/from_simulation.py
- nonos/logging.py
- nonos/main.py
- setup.cfg
> ENH: switch to loguru to support mutliprocessing + logging

- nonos/api/__init__.py
- nonos/logging.py
Simple quick review: is it robust that way ?
> prescribe level 30 for logger in api __init__.py

- .flake8
I think I was tired yesterday when I wrote #137 ...
> MNT: drop unused .flake8 config

- tests/test_load_data.py
> TST: fix test side effects (avoid creating data files while testing)

- docs/api.md
- nonos/api/_angle_parsing.py
- nonos/api/analysis.py
- nonos/api/from_simulation.py
- nonos/api/satellite.py
- nonos/main.py
- tests/test_plotting.py
> ENH : general corotation

- nonos/_backports.py
- nonos/api/from_simulation.py
- pyproject.toml
> RFC: typecheck-time verification that all codes are covered

- .github/workflows/ci.yml
- requirements/docs.txt
> DOC: test docs build in CI

- .github/workflows/ci.yml
- requirements/docs.txt
> DOC: update requirements

- nonos/api/analysis.py
- tests/test_load_data.py
> ENH: add a convenience `nfields` property to `GasDataSet`

- tests/test_params_usage.py
fix a monstruosity commited by me 3yrs ago
> TST: improve failure modes in test_params_usage

- nonos/api/analysis.py
GasField class - rotate method
> ENH: can rotate 2D and 3D data, not just 2D

- .pre-commit-config.yaml
- nonos/api/analysis.py
- nonos/parsing.py
- pyproject.toml
- **MNT: upgrade pre-commit hooks**
- **STY: stylistic changes from black 24.2.0**
- **MNT: migrate ruff config**
> MNT: manual upgrade for pre-commit

- nonos/api/analysis.py
- pyproject.toml
- tests/test_load_data.py
corrected directory of saved files using its absolute path
added test test_roundtrip_current_dir
> BUG-FIX: when copy inifile in save method if current directory

- .github/workflows/ci.yml
This is not immediately useful, but soon will be (taking small bits from my on-going refactor)
> TYP: run mypy against tests too

- nonos/api/satellite.py
> MNT: fix placement of coverage directive

- nonos/parsing.py
- tests/test_parsing.py
- **TST: add missing test cases for parse_output_number_range**
- **TST: add tests for userval_or_default**
- **TST: add missing test cases for parsing functions**
> TST: add missing test cases for parsing functions

- nonos/api/analysis.py
- tests/test_plotting.py
> BUG: fix a regression in GasField.map (revert #189)

- nonos/_readers/binary.py
found this one while looking for something broken in #295
> BUG: fix a broken fstring

- .github/workflows/ci.yml
- .readthedocs.yaml
- nonos/_backports.py
- nonos/_readers/_base.py
- nonos/_readers/binary.py
- nonos/_readers/planet.py
- nonos/_types.py
- nonos/api/_angle_parsing.py
- nonos/api/analysis.py
- nonos/api/from_simulation.py
- nonos/loaders.py
- nonos/main.py
- nonos/parsing.py
- nonos/styling.py
- pyproject.toml
- requirements/typecheck.txt
- tests/test_interfaces/test_contracts.py
- tests/test_interfaces/test_loader.py
- tests/test_interfaces/test_recipes.py
- tests/test_parameters.py
to be discussed
for context: #298
> CLN: drop support for Python 3.8

- README.md
I forgot to update this badge in #299. In practice this always happen and I don't think it's worth the additional effort, so let's just kill it !
> DOC: cleanup out-of-sync badge

- nonos/_readers/binary.py
- nonos/_types.py
- nonos/api/analysis.py
- nonos/main.py
In prep for an important refactor in Coordinates
> RFC: drop UNSET Geometry enum member

- nonos/api/analysis.py
- tests/test_load_data.py
also serves as regression tests for PR #327
> ENH: return path to saved file in GasField.save

- nonos/api/analysis.py
Based off #336
cherry-picked from #332
> RFC: simplify array transformation logic in `GasField.map`

- .github/workflows/ci.yml
xref: https://github.com/actions/upload-artifact/releases/tag/v4.4.0
> MNT: fixup coverage reporting

- .pre-commit-config.yaml
- _typos.toml
- nonos/_readers/binary.py
- nonos/api/from_simulation.py
- nonos/parsing.py
- nonos/styling.py
- tests/test_interfaces/test_contracts.py
- tests/test_parsing.py
- tests/test_readme.py
- **MNT: configure typo fixer**
- **MNT: auto fix typos**
> MNT: auto fix typos

- tests/test_image_comp.py
> RFC: avoid pyplot interface in tests (2/3)

- tests/conftest.py
Alternative to #369 
close #369 
close #363
> TST: avoid pyplot interface in tests (3/3)

- nonos/_readers/binary.py
- nonos/_readers/planet.py
- tests/test_interfaces/test_contracts.py
> RFC: avoid abstract base classes (abc), prefer composition

- nonos/api/_angle_parsing.py
- nonos/api/analysis.py
- tests/test_parsing.py
I get 45 errors on main, 22 on this branch. At least part of the remaining errors are \
not trivial to fix so I'll leave them for another day.
> TYP: fix ~20 errors discovered with pyright

- nonos/api/analysis.py
- nonos/api/satellite.py
- nonos/main.py
> RFC: refactor `Plotable` around typed data structures

- .github/workflows/ci.yml
- pyproject.toml
- src/nonos/_backports.py
- src/nonos/_types.py
- src/nonos/api/analysis.py
- src/nonos/loaders.py
- src/nonos/main.py
- tests/test_image_comp.py
- tests/test_interfaces/test_contracts.py
- uv.lock
- **TST: fix a typo**
- **TST: add numexpr to test deps**
- **RFC: simplify an if/else tree**
- **add missing pragma directives**
> TST: small coverage improvements

- src/nonos/main.py
- src/nonos/parsing.py
This fixes 6/13 errors reported by pyright for `main.py`
> TYP: improve type checking in `process_field` function

- src/nonos/api/from_simulation.py
This fixes the only remaining pyright error not already fixed in #332 or #405
> TYP: fix an isolated pyright error

- pyproject.toml
- src/nonos/api/satellite.py
- tests/test_api.py
- uv.lock
> DEP: drop `scipy` as a hard dependency

- pyproject.toml
> BLD: require flit-core 3.11 or newer

- .github/workflows/bleeding-edge.yml
- .github/workflows/cd.yml
replace `actions/setup-python` with `astral-sh/setup-uv`
> TST: CI simplifications

- pyproject.toml
- src/nonos/_geometry.py
- src/nonos/_readers/binary.py
- src/nonos/_types.py
- src/nonos/api/__init__.py
- src/nonos/api/analysis.py
- src/nonos/api/satellite.py
- src/nonos/main.py
- tests/test_geometry.py
- tests/test_image_comp.py
- tests/test_interfaces/test_recipes.py
- tests/test_load_data.py
This is a work in progress. I am not even done defining the scope of this refactor, and there are some failing tests. I'm opening the PR so I don't forget about this branch.
> RFC: refactor Coordinates class into a separate module

- README.md
- src/nonos/_geometry.py
- tests/test_readme.py
> CLN: cleanup a couple inline TODO comments

- README.md
- pyproject.toml
- uv.lock
> REL: prepare release 0.18.0

- .github/renovate.json5
> MNT: configure Renovate

- .github/workflows/ci.yml
```
Key Validation Error: setup-uv-1-x86_64-unknown-linux-gnu-3.10-9602bc1ffafe484ddc89185beb66bf6e0e1adb1eb6cf988ad2639fde2b248bb6-(oldest deps, full) cannot contain commas.
```
> TST: fixup broken CI caching

- cli/pyproject.toml
- cli/src/nonos_cli/__init__.py
- cli/src/nonos_cli/logging.py
- cli/tests/test_cli.py
- uv.lock
> DEP: re-implement warning and error message in loguru (ditch termcolor)

- README.md
> DOC: advertise development status instead a plain 'WIP' sign

- CITATION.cff
- scripts/pre_publish_checks.py
> REL: prepare releases (nonos 0.19.0 + nonos-cli 0.1.0)

- .github/workflows/build-and-publish.yml
- .github/workflows/cd.yml
> REL: prepare releases (nonos 0.19.0 + nonos-cli 0.1.0) (tentative fixup)
